apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-optimizer
  namespace: default
  labels:
    app: resource-optimizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-optimizer
  template:
    metadata:
      labels:
        app: resource-optimizer
    spec:
      serviceAccountName: resource-optimizer-sa
      containers:
      - name: resource-optimizer
        image: resource-optimizer:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        envFrom:
        - configMapRef:
            name: resource-optimizer-config
        volumeMounts:
        - name: model-storage
          mountPath: /app/models
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: resource-optimizer-pvc 