apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-optimizer
  namespace: default
  labels:
    app: resource-optimizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-optimizer
  template:
    metadata:
      labels:
        app: resource-optimizer
    spec:
      serviceAccountName: resource-optimizer-sa
      containers:
      - name: resource-optimizer
        image: your-registry/resource-optimizer:latest
        ports:
        - containerPort: 8501
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        envFrom:
        - configMapRef:
            name: resource-optimizer-config
        volumeMounts:
        - name: models
          mountPath: /app/models
      volumes:
      - name: models
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: resource-optimizer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8501
  selector:
    app: resource-optimizer 