apiVersion: v1
kind: ServiceAccount
metadata:
  name: resource-optimizer-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-optimizer-role
rules:
- apiGroups: [""]
  resources: ["nodes", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resource-optimizer-binding
subjects:
- kind: ServiceAccount
  name: resource-optimizer-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: resource-optimizer-role
  apiGroup: rbac.authorization.k8s.io 